<?php 
/* ********************************************************************* 
 * Auto Generated Code - Do not Edit
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.
 *
 * ********************************************************************* */
/* --------------------------------------------------

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.

If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.
-------------------------------------------------- */

 function _H31($thisuseragent){
$patterns = array("#(?<=BlackBerry)[^;]+#" => 100000,"#(?<=Version/)\d+\.\d+\.\d+#" => 10);
$ls = PHP_INT_MAX;
$segmentMatches = F51DRegexSegment($thisuseragent, $patterns);
$dl = array();
$testSegments = array();
$weights = array();
$uaCount=count($segmentMatches);
for($i = 0; $i < $uaCount; $i++)
{
	foreach ($segmentMatches[$i] as $currentThis)
	{
		foreach ($currentThis as $uaSeg => $ow)
		{
			$testSegments[$i][] = $uaSeg;
			$weights[$i] = $ow;
		}
	}
}
$segmentMatches = array($testSegments, $weights);
$va0 = array(" 9800"," 9780"," 9300"," 9700"," 9900"," 9810"," 9650"," 9360"," 9330"," 9860"," 9670"," 9930"," 9850"," 9790"," 9105"," 9100"," 9350"," 9380"," 9370"," 9981"," 9788"," 9570"," 8980"," 8520"," 9220");$va1 = array("6.0.0","7.0.0","7.1.0","6.1.0");
  $ns = E31($segmentMatches, array(array($va0[0]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14523","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9800; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.246 Mobile Safari/534.1+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[1]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14929","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9780; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.448 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[2]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15722","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9300; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.448 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[3]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("11730","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9700; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.448 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[4]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15259","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.261 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[5]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15232","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9810; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.261 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[6],$va0[6]),array($va1[0],$va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14888","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9650; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.524 Mobile Safari/534.8+, Mozilla/5.0 (BlackBerry; U; BlackBerry 9650; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.524 Mobile Safari/53");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[6]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14888","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9650; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.524 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[7]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15250","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9360; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.319 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[8],$va0[8]),array($va1[0],$va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15234","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9330; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.415 Mobile Safari/534.1+, Mozilla/5.0 (BlackBerry; U; BlackBerry 9330; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.415 Mobile Safari/53");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[8]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15234","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9330; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.524 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[9]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13144","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9860; en-GB) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.296 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[10]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15745","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9670; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.522 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[10],$va0[10]),array($va1[0],$va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15745","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9670; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.407 Mobile Safari/534.1+, Mozilla/5.0 (BlackBerry; U; BlackBerry 9670; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.407 Mobile Safari/53");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[4]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15259","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.284 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[11]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15236","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9930; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.254 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[12]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15263","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.261 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[13]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13062","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9790; en-GB) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.528 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[11]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15236","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9930; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.163 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[14]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13341","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9105; en-GB) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.570 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[15]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13783","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9100; en) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.481 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[16]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12628","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9350; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.261 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[5]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15232","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9810; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.267 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[12]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15263","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.163 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[17]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12825","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9380; en-GB) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.513 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[9]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13144","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9860; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.267 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[18]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12779","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9370; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.374 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[7]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15250","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9360; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.258 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[19]),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15254","6374","4418","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9981; en-GB) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.0.0.579 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[13]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13062","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9790; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.247 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[17]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12825","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9380; en-GB) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.336 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[5]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15232","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9810; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0.50 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[16]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12628","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9350; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.342 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[9]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13144","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9860; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0.60 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[4]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15259","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9900; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0.74 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[20]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12705","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9788; zh-CN) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.673 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[21]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13665","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9570; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.250 Mobile Safari/534.1+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[16]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12628","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9350; en-US) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.1.0.32 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[12]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15263","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9850; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0.73 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[22]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12718","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 8980; en) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0.401 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[5]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15232","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9810; en-GB) AppleWebKit/534.8+ (KHTML, like Gecko) Version/6.0.0 Mobile Safari/534.8+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[23]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15216","5156","3519","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 8520; en-US) AppleWebKit/534.1+ (KHTML, like Gecko) Version/6.0.0.141 Mobile Safari/534.1+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[11]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15236","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9930; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0.46 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[7]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15250","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9360; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0.52 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[19]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15254","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9981; en) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.190 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[24]),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18285","7106","15829","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9220; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/7.1.0.263 Mobile Safari/534.11+");$ls = $ns;}
  $ns = E31($segmentMatches, array(array($va0[18]),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12779","6661","4453","18092", "Mozilla/5.0 (BlackBerry; U; BlackBerry 9370; en-US) AppleWebKit/534.11+ (KHTML, like Gecko) Version/6.1.0 Mobile Safari/534.11+");$ls = $ns;}
 return $dl;}
function E31(&$thisUA, $toTest, &$ls)
{
	$deviceTotal = 0;$uaCount=count($thisUA[0]);
	for($i = 0; $i < $uaCount; $i++){$segCount = count($thisUA[0][$i]);if($segCount != count($toTest[$i])){return PHP_INT_MAX;}
	for($ind = 0; $ind < $segCount; $ind++){$deviceTotal += (F51DEditDistance($thisUA[0][$i][$ind], $toTest[$i][$ind], $ls) * $thisUA[1][$i]);if($deviceTotal > $ls){return $deviceTotal;}}}
	return $deviceTotal;
}
 ?>
