<?php 
/* ********************************************************************* 
 * Auto Generated Code - Do not Edit
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.
 *
 * ********************************************************************* */
/* --------------------------------------------------

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.

If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.
-------------------------------------------------- */

 function _H38($thisuseragent){
$patterns = array("#(?<=Mozilla/)[\d\.]+#" => 1,"#(?<=Fennec/)[\d\.]+#" => 1,"#Fennec#" => 1,"#(?<=\()[^\)]+#" => 5,"#(?<=Gecko/)[\d]+#" => 5,"#(?<=Firefox/)[\d\.]+#" => 5);
$ls = PHP_INT_MAX;
$segmentMatches = F51DRegexSegment($thisuseragent, $patterns);
$dl = array();
$testSegments = array();
$weights = array();
$uaCount=count($segmentMatches);
for($i = 0; $i < $uaCount; $i++)
{
	foreach ($segmentMatches[$i] as $currentThis)
	{
		foreach ($currentThis as $uaSeg => $ow)
		{
			$testSegments[$i][] = $uaSeg;
			$weights[$i] = $ow;
		}
	}
}
$segmentMatches = array($testSegments, $weights);
$va0 = array("5.0");$va1 = array("1.1","4.0","12.0","4.0.1","2.0.1","13.0","11.0","10.0","10.0.2","1.0");$va2 = array("Fennec");$va3 = array("X11; U; Linux armv7l; en-US; rv:1.9.2.5","Maemo; Linux armv7l; rv:2.1","Maemo; Linux armv7l; rv:12.0","Windows NT 6.1; WOW64; rv:2.1.1","Windows NT 6.1; rv:2.1.1","Android; Linux armv7l; rv:2.0b7pre","Android; Linux armv7l; rv:2.0b8","Android; Linux armv7l; rv:2.0b11pre","Android; Linux armv7l; rv:2.1","Android; Linux armv7l; rv:2.0b12pre","Android; Linux armv7l; rv:2.1.1","Android; Linux armv7l; rv:12.0a1","Android; Linux armv7l; rv:2.0.1","Android; Tablet; rv:12.0","Android; Mobile; rv:12.0","Android; Tablet; rv:13.0","Android; Mobile; rv:13.0","Android; Linux armv7l; rv:11.0a2","Android; Linux armv7l; rv:11.0","Android; Mobile; rv:11.0","Maemo; Linux armv7l; rv:10.0a1","Maemo; Linux armv7l; rv:10.0.2","Windows; U; Windows CE 5.2; en-US; rv:1.9.2a1pre");$va4 = array("12","13","11","20090513");$va5 = array("3.6.5","4.0","12.0","4.0.2","13.0","11.0","10.0","10.0.2");
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0]),array($va3[0]),array(""),array($va5[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","17470","18092", "Mozilla/5.0 (X11; U; Linux armv7l; en-US; rv:1.9.2.5) Gecko/X Firefox/3.6.5pre Fennec/1.1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[0]),array($va3[1]),array(""),array($va5[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","17470","18092", "Mozilla/5.0 (Maemo; Linux armv7l; rv:2.1) Gecko/X Firefox/4.0b13pre Fennec/4.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[2]),array($va2[0]),array($va3[2]),array(""),array($va5[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","17470","18092", "Mozilla/5.0 (Maemo; Linux armv7l; rv:12.0) Gecko/X Firefox/12.0 Fennec/12.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[0]),array($va3[3]),array(""),array($va5[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","7133","17470","18092", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.1.1) Gecko/X Firefox/4.0.2pre Fennec/4.0.1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[0]),array($va3[4]),array(""),array($va5[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","7133","17470","18092", "Mozilla/5.0 (Windows NT 6.1; rv:2.1.1) Gecko/X Firefox/4.0.2pre Fennec/4.0.1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[0]),array($va3[5]),array(""),array($va5[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.0b7pre) Gecko/X Firefox/4.0b8pre Fennec/4.0b2");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[0]),array($va3[6]),array(""),array($va5[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.0b8) Gecko/X Firefox/4.0b8 Fennec/4.0b3");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[0]),array($va3[7]),array(""),array($va5[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.0b11pre) Gecko/X Firefox/4.0b11pre Fennec/4.0b4");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[0]),array($va3[8]),array(""),array($va5[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.1) Gecko/X Firefox/4.0b13pre Fennec/4.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[0]),array($va3[9]),array(""),array($va5[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.0b12pre) Gecko/X Firefox/4.0b12pre Fennec/4.0b5");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[0]),array($va3[10]),array(""),array($va5[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.1.1) Gecko/X Firefox/4.0.2pre Fennec/4.0.1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[2]),array($va2[0]),array($va3[11]),array(""),array($va5[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:12.0a1) Gecko/X Firefox/12.0a1 Fennec/12.0a1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[4]),array($va2[0]),array($va3[12]),array(""),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:2.0.1) Gecko/X Fennec/2.0.1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[2]),array($va2[0]),array($va3[13]),array($va4[0]),array($va5[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Tablet; rv:12.0) Gecko/12.0 Firefox/12.0 Fennec/12.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[2]),array($va2[0]),array($va3[14]),array($va4[0]),array($va5[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Mobile; rv:12.0) Gecko/12.0 Firefox/12.0 Fennec/12.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[5]),array($va2[0]),array($va3[15]),array($va4[1]),array($va5[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Tablet; rv:13.0) Gecko/13.0 Firefox/13.0 Fennec/13.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[5]),array($va2[0]),array($va3[16]),array($va4[1]),array($va5[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","17470","18092", "Mozilla/5.0 (Android; Mobile; rv:13.0) Gecko/13.0 Firefox/13.0 Fennec/13.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[6]),array($va2[0]),array($va3[17]),array(""),array($va5[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","18186","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:11.0a2) Gecko/X Firefox/11.0a2 Fennec/11.0a2");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[6]),array($va2[0]),array($va3[18]),array(""),array($va5[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","18186","18092", "Mozilla/5.0 (Android; Linux armv7l; rv:11.0) Gecko/X Firefox/11.0 Fennec/11.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[6]),array($va2[0]),array($va3[19]),array($va4[2]),array($va5[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17968","17979","18186","18092", "Mozilla/5.0 (Android; Mobile; rv:11.0) Gecko/11.0 Firefox/11.0 Fennec/11.0");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[7]),array($va2[0]),array($va3[20]),array(""),array($va5[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","18160","18092", "Mozilla/5.0 (Maemo; Linux armv7l; rv:10.0a1) Gecko/X Firefox/10.0a1 Fennec/10.0a1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[8]),array($va2[0]),array($va3[21]),array(""),array($va5[7])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","18160","18092", "Mozilla/5.0 (Maemo; Linux armv7l; rv:10.0.2) Gecko/X Firefox/10.0.2 Fennec/10.0.2");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[9]),array($va2[0]),array($va3[22]),array($va4[3]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5448","15761","18092", "Mozilla/5.0 (Windows; U; Windows CE 5.2; en-US; rv:1.9.2a1pre) Gecko/20090513 Fennec/1.0a1");$ls = $ns;}
  $ns = E38($segmentMatches, array(array($va0[0]),array($va1[9]),array($va2[0]),array($va3[22]),array(""),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5448","15761","18092", "Mozilla/5.0 (Windows; U; Windows CE 5.2; en-US; rv:1.9.2a1pre) Gecko/X Fennec/1.0a1");$ls = $ns;}
 return $dl;}
function E38(&$thisUA, $toTest, &$ls)
{
	$deviceTotal = 0;$uaCount=count($thisUA[0]);
	for($i = 0; $i < $uaCount; $i++){$segCount = count($thisUA[0][$i]);if($segCount != count($toTest[$i])){return PHP_INT_MAX;}
	for($ind = 0; $ind < $segCount; $ind++){$deviceTotal += (F51DEditDistance($thisUA[0][$i][$ind], $toTest[$i][$ind], $ls) * $thisUA[1][$i]);if($deviceTotal > $ls){return $deviceTotal;}}}
	return $deviceTotal;
}
 ?>
