<?php 
/* ********************************************************************* 
 * Auto Generated Code - Do not Edit
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.
 *
 * ********************************************************************* */
/* --------------------------------------------------

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.

If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.
-------------------------------------------------- */

 function _H51($thisuseragent){
 $segmentMatches = $thisuseragent;$ls = PHP_INT_MAX;$dl = array();
 return $dl;}
function E51(&$thisUA, $UAToTest, &$ls)
{
	return F51DEditDistance($thisUA, $UAToTest, $ls);
}
 ?>
