<?php 
/* ********************************************************************* 
 * Auto Generated Code - Do not Edit
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.
 *
 * ********************************************************************* */
/* --------------------------------------------------

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.

If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.
-------------------------------------------------- */

 function _H63($thisuseragent){
$patterns = array("#(?<=Opera Mini/att/)\d\.\d#" => 1,"#^[^;]+#" => 1);
$ls = PHP_INT_MAX;
$segmentMatches = F51DRegexSegment($thisuseragent, $patterns);
$dl = array();
$testSegments = array();
$weights = array();
$uaCount=count($segmentMatches);
for($i = 0; $i < $uaCount; $i++)
{
	foreach ($segmentMatches[$i] as $currentThis)
	{
		foreach ($currentThis as $uaSeg => $ow)
		{
			$testSegments[$i][] = $uaSeg;
			$weights[$i] = $ow;
		}
	}
}
$segmentMatches = array($testSegments, $weights);
$va0 = array("4.2");$va1 = array("Z221","Opera/9.60 (J2ME/MIDP","Opera/9.50 (J2ME/MIDP","Opera/9.80 (VRE","Opera/9.80 (J2ME/MIDP","aaaOpera/9.50 (J2ME/MIDP","Opera/9.80 (MTK","Opera/10.61 (J2ME/MIDP","Opera/9.80 (Series 60","Opera/9.80 (Bada","lg-kf750-v10a browser/obigo-q05a/3.12 mms/lg-mms-v1.0/1.2 java/asvm/1.1 profile/midp-2.1 configuration/cldc-1.1","Opera/8.01 (J2ME/MIDP","Opera/9.80 (Windows Mobile","Opera/9.80 (BREW");
  $ns = E63($segmentMatches, array(array($va0[0]),array($va1[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4732","18092", "Z221; Mozilla/5.0 (Profile/MIDP-2.0 Configuration/CLDC-1.1; Opera Mini/att/4.2.22250; U; en-US) Opera 9.50");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4732","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/4.2.13337/504; U; ru) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4732","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/4.2.24756/26.1532; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4732","18092", "Opera/9.80 (VRE; Opera Mini/4.2.75/27.1573; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4732","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/4.2.20464/27.1597; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4307","18092", "aaaOpera/9.50 (J2ME/MIDP; Opera Mini/4.1.11355/542; U; en) UP.Browser/7.0.2.3.119 (GUI) MMP/2.0 Push/PO");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4307","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/4.1.13961/546; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4307","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/4.1.11320/608; U; en) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4307","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/4.1.15082/27.1573; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17371","18092", "Opera/9.80 (MTK; Opera Mini/5.1.3086/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[7])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17371","18092", "Opera/10.61 (J2ME/MIDP; Opera Mini/5.1.21219/19.999; en-US; rv:1.9.3a5) WebKit/534.5 Presto/2.6.30");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17371","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/5.1.2146/26.1532; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17371","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/5.1.24009/27.1597; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17369","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/4.4.14881/960; U; en) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17369","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/4.4.29476/27.1597; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","17373","18092", "Opera/9.80 (Series 60; Opera Mini/6.5.27354/27.1573; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17373","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/6.5.28416/26.1532; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17373","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/6.5.26955/27.1597; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[9])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17373","18092", "Opera/9.80 (Bada; Opera Mini/6.5.11/27.1597; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","17780","18092", "Opera/9.80 (Series 60; Opera Mini/6.1.26266/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4719","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/4.3.13221/504; U; en) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4719","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/4.3.25172/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","4860","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/6.24093/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17372","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/5.21463/25.925; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17372","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/5.22371/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[10])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17780","18092", "lg-kf750-v10a browser/obigo-q05a/3.12 mms/lg-mms-v1.0/1.2 java/asvm/1.1 profile/midp-2.1 configuration/cldc-1.1; Opera/9.50 (J2ME/MIDP; Opera Mini/4.0.10269/hifi/tmobile/uk; en; U)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17780","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini/1.1.2666/1724; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17780","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/6.1.25378/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17780","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/6.1.27786/26.1467; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","4860","18092", "Opera/9.80 (Series 60; Opera Mini/6.24455/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[12])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18182","5448","17371","18092", "Opera/9.80 (Windows Mobile; Opera Mini/5.1.21594/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17368","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini/3.1.10423/1724; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","17371","18092", "Opera/9.80 (Series 60; Opera Mini/5.1.22783/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18255","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/7.28870/27.1407; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18255","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/7.29530/26.1532; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","18255","18092", "Opera/9.80 (Series 60; Opera Mini/7.28965/27.1366; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18123","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini/2.0.4509/1724; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18057","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.1.191/26.1521; U; en) Presto/2.8.119 400X240 LG VN271");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18122","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18122","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18122","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5567","17780","18092", "Opera/9.80 (BREW; Opera Mini/6.143/27.1597; U; id) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17470","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/1.0.13057/866; U; en) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17470","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/4.0.15081/20.2485; U; en) Presto/2.5.25");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17470","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/4.0.10822/546; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17470","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini/1.1.3095/1662; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18159","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/5.3521/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18332","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/2.1; http:/19.864; U; en) Presto/2.5.25");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18332","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/2.1141/26.1208; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18332","18092", "Opera/9.80 (MTK; Opera Mini/2.1198/27.1573; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.1.189/26.1319; U; en) Presto/2.8.119 400X240 LG VN271");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5567","17370","18092", "Opera/9.80 (BREW; Opera Mini/5/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","15774","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/4.8462/27.1530; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17367","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini/3.0.6306/1724; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("16488","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.1.182/26.1319; U; en) Presto/2.8.119 240X400 Pantech CDM8992");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18274","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/9.5.Turbo Silver/416; U; en) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","18274","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/9.5/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17370","18092", "Opera/9.50 (J2ME/MIDP; Opera Mini/5.0.21463/20.2707; U; en)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17370","18092", "Opera/8.01 (J2ME/MIDP; Opera Mini/5.0.10423/1724; en; U; ssr)");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17370","18092", "Opera/9.60 (J2ME/MIDP; Opera Mini/5.0.15650/446; U; en) Presto/2.2.0");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","17017","17370","18092", "Opera/9.80 (J2ME/MIDP; Opera Mini/5.0.17443/24.746; U; en) Presto/2.5.25 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5567","4732","18092", "Opera/9.80 (BREW; Opera Mini/4.2.99/26.1305; U; id) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("16519","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.1.182/26.1319; U; en) Presto/2.8.119 320X240 Pantech TXT8045");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","17470","18092", "Opera/9.80 (Series 60; Opera Mini/6.6.29184/27.1530; U; en) Presto/2.8.119 Version/11.10");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14663","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.10/26.1434; U; en) Presto/2.8.119 320X240 LG VX9200");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12355","5567","17470","18092", "Opera/9.80 (BREW; Opera Mini/5.43/26.1521; U; en) Presto/2.8.119 320X240 LG VN250");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","17372","18092", "Opera/9.80 (Series 60; Opera Mini/5.2.22784/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("13856","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.1.173/26.1434; U; en) Presto/2.8.119 400X240 LG VN270");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[13])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12092","5567","17371","18092", "Opera/9.80 (BREW; Opera Mini/5.16/26.1434; U; en) Presto/2.8.119 800X480 LG VX11000");$ls = $ns;}
  $ns = E63($segmentMatches, array(array(""),array($va1[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18095","18109","18274","18092", "Opera/9.80 (Series 60; Opera Mini/9.5.27310/26.1305; U; en) Presto/2.8.119 Version/10.54");$ls = $ns;}
 return $dl;}
function E63(&$thisUA, $toTest, &$ls)
{
	$deviceTotal = 0;$uaCount=count($thisUA[0]);
	for($i = 0; $i < $uaCount; $i++){$segCount = count($thisUA[0][$i]);if($segCount != count($toTest[$i])){return PHP_INT_MAX;}
	for($ind = 0; $ind < $segCount; $ind++){$deviceTotal += (F51DEditDistance($thisUA[0][$i][$ind], $toTest[$i][$ind], $ls) * $thisUA[1][$i]);if($deviceTotal > $ls){return $deviceTotal;}}}
	return $deviceTotal;
}
 ?>
