<?php 
/* ********************************************************************* 
 * Auto Generated Code - Do not Edit
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.
 *
 * ********************************************************************* */
/* --------------------------------------------------

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.

If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

This Source Code Form is “Incompatible With Secondary Licenses”, as defined by the Mozilla Public License, v. 2.0.
-------------------------------------------------- */

 function _H94($thisuseragent){
$patterns = array("#(?<=Mozilla/)\d\.\d#" => 100000,"#(?<=Mozilla/\d\.\d \()[^;\)]+#" => 10000,"#Windows NT \d\.\d(?=;)|Mac OS X [^\s]+(?=;)|Ubuntu|X11#" => 10000);
$ls = PHP_INT_MAX;
$segmentMatches = F51DRegexSegment($thisuseragent, $patterns);
$dl = array();
$testSegments = array();
$weights = array();
$uaCount=count($segmentMatches);
for($i = 0; $i < $uaCount; $i++)
{
	foreach ($segmentMatches[$i] as $currentThis)
	{
		foreach ($currentThis as $uaSeg => $ow)
		{
			$testSegments[$i][] = $uaSeg;
			$weights[$i] = $ow;
		}
	}
}
$segmentMatches = array($testSegments, $weights);
$va0 = array("5.0","4.8");$va1 = array("X11","Windows","Windows NT 5.1","Macintosh","Windows NT 6.1");$va2 = array("X11","Windows NT 5.1","Windows NT 5.2","Mac OS X Mach-O","Mac OS X 10.6","Windows NT 6.1","Ubuntu","Windows NT 6.0","Mac OS X 10.5","Windows NT 5.0","Mac OS X 10.7","Mac OS X 10.4");
  $ns = E94($segmentMatches, array(array($va0[0]),array(""),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","17470","18092", "Mozilla/5.0 Galeon/1.0.2 (X11; Linux i686; U;) Gecko/X");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18110","17470","18092", "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9) Gecko");$ls = $ns;}
  $ns = E94($segmentMatches, array(array(""),array(""),array($va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5690","17470","18092", "K-Meleon/0.6 (Windows; U; Windows NT 5.1; en-US; rv:0.9.5) Gecko/X");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[2])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5690","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US; rv:1.9.1.7) Gecko/201");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5690","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.17pre) Gecko K-Meleon/1.6.0");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0],$va0[1]),array($va1[1]),array($va2[1],$va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5690","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.3) Gecko/X Mozilla/4.8 [en] (Windows NT 5.1; U)");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[2]),array($va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5690","17470","18092", "Mozilla/5.0 (Windows NT 5.1; rv:7.0.1) Gecko/X SeaMonkey/2.4.1");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","18120","17470","18092", "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/X SeaMonkey/1.1.9");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[3])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","18120","17470","18092", "Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.5b) Gecko/X Camino/0.7+");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[4])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","17296","17470","18092", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0.1) Gecko/X Gimme Bar");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","7133","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.17pre) Gecko K-Meleon/1.6.0");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[4]),array($va2[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","7133","17470","18092", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/X SeaMonkey/2.9");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0],$va2[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17017","17470","18092", "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.17) Gecko/X SeaMonkey/1.1.12 (Ubuntu-1.1.12+nobinonly-0ubuntu0.8.04.1)");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17017","17470","18092", "Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.5) Gecko/X K-Meleon/0.8");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0],$va2[6],$va2[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17017","17470","18092", "Mozilla/5.0 (X11; U; Linux i686; en-GB; rv:1.7.6) Gecko/X Epiphany/1.6.1 (Ubuntu) (Ubuntu package 1.0.2)");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17017","17470","18092", "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.4) Gecko/X (Debian-1.8.1.4-2ubuntu5)");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array(""),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17017","17470","18092", "Mozilla/5.001 (X11; U; Linux i686; rv:1.8.1.6; de-ch) Gecko/X (ubuntu-feisty)");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17285","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 6.0 x64; en-US; rv:1.9pre) Gecko/X Minefield/3.0.2pre");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[7])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17285","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1.16) Gecko");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[5],$va2[5])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","7133","17217","18092", "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.13) Gecko/X Opera/9.80 (Windows NT 6.1; U; zh-tw) Presto/2.7.62 Version/11.01");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[8])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","17295","17470","18092", "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1.18) Gecko/X SeaMonkey/2.0.13");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[9])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","7127","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.9.2a1pre) Gecko");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","5690","17215","18092", "Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9b3) Gecko/X Opera 9.5");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[10])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","17297","17470","18092", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:7.0.1) Gecko/X Yoono/1.8.16");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array($va2[11])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","17294","17470","18092", "Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.4; de; rv:1.9.1.19) Gecko/X SeaMonkey/2.0.14");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","6704","17470","18092", "Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.4) Gecko Netscape/7.1 (ax)");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[3]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("17595","17017","17470","18092", "Mozilla/5.0 (Macintosh; U; PPC; en-US; rv:1.2.1) Gecko/X");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5448","17470","18092", "Mozilla/5.0 (Windows; U; Windows CE 5.2; rv:1.8.1.4pre) Gecko/20070327 Minimo/0.020");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array("")), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18088","5448","17470","18092", "Mozilla/5.0 (Windows; U; Windows CE 4.21; rv:1.8b4) Gecko/X Minimo/0.007");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18146","17470","18092", "Mozilla/5.0 (X11; U; SunOS sun4u; en-US; rv:1.4) Gecko/X");$ls = $ns;}
  $ns = E94($segmentMatches, array(array(""),array(""),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17866","17470","18092", "Seamonkey-1.1.13-1(X11; U; GNU Fedora fc 10) Gecko/X");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17866","17470","18092", "Mozilla/5.0 (X11; U; Linux i686 (x86_64); en-US; rv:1.9.2.18) Gecko Fedora/1.9.2.18-1.fc14");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0],$va2[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","17837","17470","18092", "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.14) Gecko/X Ubuntu/9.04 (jaunty) Shiretoko/3.5.14");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array(""),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18145","17470","18092", "Mozilla/5.0 http://fairshare.cc (X11; U; FreeBSD i386; en-US; rv:1.2a) Gecko/X");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("15364","18145","17470","18092", "Mozilla/5.0 (X11; U; FreeBSD amd64; en-US; rv:1.8.1.21) Gecko/X SeaMonkey/1.1.16");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12280","18110","17470","18092", "Mozilla/5.0 (X11; iPhone; Mobile; Linux i686; chrome://navigator/locale/navigator.properties; rv:1.8.0.6) Gecko/X Skylight");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("16568","18110","17470","18092", "Mozilla/5.0 (X11; Linux i686; U; en-US) Gecko/X Vision-Browser/8.1 381x214 Pantech CDM8999");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14862","5204","17348","18092", "Nokia2700c-2/2.0 (09.95) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 (X11; U; Linux i686; en) Gecko/UCWEB7.1.0.42/69/300");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("14708","5204","17348","18092", "Nokia5130c-2/2.0 (07.91) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 (Windows; U; Windows NT 5.1; en-GB; rv:1.8.1.6) Gecko/20070725/UCWEB7.1.0.42/69/351");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12473","5204","17348","18092", "Nokia2730c-1/2.0 (10.40) Profile/MIDP-2.1 Configuration/CLDC-1.1 Mozilla/5.0 (X11; U; Linux i686; en) Gecko/UCWEB7.1.0.42/69/300");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("16082","18110","17470","18092", "Mozilla/5.0 (X11; Linux i686; U; en-US) Gecko/X Vision-Browser/8.1 301x200 LG VN530");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[1]),array($va2[1])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("12280","5690","17470","18092", "Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2.13) Gecko/X iPhone");$ls = $ns;}
  $ns = E94($segmentMatches, array(array($va0[0]),array($va1[0]),array($va2[0],$va2[6])), $ls); if($ns <= $ls){if($ns < $ls){unset($dl);}$dl[] = array("18254","17017","18245","18163", "Mozilla/5.0 (X11; U; Linux i586; en-US; rv:1.7.3) Gecko/X Epiphany/1.4.4 (Ubuntu)/Nutch-1.4");$ls = $ns;}
 return $dl;}
function E94(&$thisUA, $toTest, &$ls)
{
	$deviceTotal = 0;$uaCount=count($thisUA[0]);
	for($i = 0; $i < $uaCount; $i++){$segCount = count($thisUA[0][$i]);if($segCount != count($toTest[$i])){return PHP_INT_MAX;}
	for($ind = 0; $ind < $segCount; $ind++){$deviceTotal += (F51DEditDistance($thisUA[0][$i][$ind], $toTest[$i][$ind], $ls) * $thisUA[1][$i]);if($deviceTotal > $ls){return $deviceTotal;}}}
	return $deviceTotal;
}
 ?>
