<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E0(&$target, $test, &$ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 100000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[1], $test[1], $ls, 1, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H0($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#(?<=Alcatel-)[^/\\s]+#', $useragent),
    1 => fiftyone_degrees_preg_match_all('#.+#', $useragent));
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'ALCATEL-OT871A/980 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1196444,138369,97064,913, 'ALCATEL-OT871A/980 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '22965-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'ALCATEL-OT871A/984 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1196444,138369,97064,913, 'ALCATEL-OT871A/984 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '22965-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606A'), 1 => array(0 => 'Alcatel-OT-606A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201349,138369,98811,913, 'Alcatel-OT-606A/1.0 ObigoInternetBrowser/Q03C', '14455-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606A'), 1 => array(0 => 'Alcatel-OT-606A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201349,138369,98811,913, 'Alcatel-OT-606A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14455-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/010_05 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201349,138369,98811,913, 'Alcatel-OT-606/010_05 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14455-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201349,138369,98811,913, 'Alcatel-OT-606/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14455-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-606'), 1 => array(0 => 'Alcatel-OT-606/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201349,138369,98811,913, 'Alcatel-OT-606/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14455-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'ALCATEL-OT510A/382 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1041456,138369,97064,913, 'ALCATEL-OT510A/382 ObigoInternetBrowser/Q05A', '19754-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(253621,138369,97064,913, 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14572-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(253621,138369,97064,913, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14572-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800A', 1 => 'OT-800A'), 1 => array(0 => 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(253621,138369,97064,913, 'Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14572-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800', 1 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(253621,138369,97064,913, 'Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-800/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14572-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-800'), 1 => array(0 => 'Alcatel-OT-800/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(253621,138369,97064,913, 'Alcatel-OT-800/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14572-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802A'), 1 => array(0 => 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(311507,138369,97064,913, 'Alcatel-OT-802A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13785-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802Y'), 1 => array(0 => 'Alcatel-OT-802Y/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(311507,138369,97064,913, 'Alcatel-OT-802Y/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13785-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-802'), 1 => array(0 => 'Alcatel-OT-802/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(311507,138369,97064,913, 'Alcatel-OT-802/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13785-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355A'), 1 => array(0 => 'Alcatel-OT-355A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201277,138369,98811,913, 'Alcatel-OT-355A/1.0 ObigoInternetBrowser/Q03C', '14135-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355D'), 1 => array(0 => 'Alcatel-OT-355D/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201277,138369,98811,913, 'Alcatel-OT-355D/1.0 ObigoInternetBrowser/Q03C', '14135-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 model-bouygues ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201277,138369,98811,913, 'Alcatel-OT-355/1.0 model-bouygues ObigoInternetBrowser/Q03C', '14135-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201277,138369,98811,913, 'Alcatel-OT-355/1.0 model-orange ObigoInternetBrowser/Q03C', '14135-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-355'), 1 => array(0 => 'Alcatel-OT-355/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201277,138369,98811,913, 'Alcatel-OT-355/1.0 ObigoInternetBrowser/Q03C', '14135-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'ALCATEL_ONE_TOUCH_838/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1171643,1171715,97064,913, 'ALCATEL_ONE_TOUCH_838/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1ObigoInternetBrowser/Q05A', '20025-22849-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_4010X) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,90522,645789,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_4010X) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '15364-5629-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_4010D) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,90522,645789,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_4010D) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '15364-5629-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/010_02 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(138297,138369,97064,913, 'Alcatel-OT-808/010_02 1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12420-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808', 1 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(138297,138369,97064,913, 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A, Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12420-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808A'), 1 => array(0 => 'Alcatel-OT-808A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(138297,138369,97064,913, 'Alcatel-OT-808A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12420-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-808'), 1 => array(0 => 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(138297,138369,97064,913, 'Alcatel-OT-808/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12420-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710A'), 1 => array(0 => 'Alcatel-OT-710A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350077,138369,98811,913, 'Alcatel-OT-710A/1.0 ObigoInternetBrowser/Q03C', '14151-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710A'), 1 => array(0 => 'Alcatel-OT-710A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350077,138369,98811,913, 'Alcatel-OT-710A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14151-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710', 1 => 'OT-710'), 1 => array(0 => 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350077,138369,98811,913, 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14151-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710'), 1 => array(0 => 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350077,138369,98811,913, 'Alcatel-OT-710/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14151-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-710D'), 1 => array(0 => 'Alcatel-OT-710D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(350077,138369,98811,913, 'Alcatel-OT-710D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '14151-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.6.0.276 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1016432,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.6.0.276 U2/1.0.0 Mobile', '18510-5629-18527-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.6.0.318 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1016432,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.6.0.318 U2/1.0.0 Mobile', '18510-5629-18527-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255', 1 => 'OT-255'), 1 => array(0 => 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(173649,138369,98811,913, 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C', '13544-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255A'), 1 => array(0 => 'Alcatel-OT-255A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(173649,138369,98811,913, 'Alcatel-OT-255A/1.0 ObigoInternetBrowser/Q03C', '13544-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255'), 1 => array(0 => 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(173649,138369,98811,913, 'Alcatel-OT-255/1.0 ObigoInternetBrowser/Q03C', '13544-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-255D'), 1 => array(0 => 'Alcatel-OT-255D/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(173649,138369,98811,913, 'Alcatel-OT-255D/1.0 ObigoInternetBrowser/Q03C', '13544-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OH5'), 1 => array(0 => 'Alcatel-OH5/1.0 UP.Browser/6.1.0.7.7 (GUI) MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(417085,138369,205920,913, 'Alcatel-OH5/1.0 UP.Browser/6.1.0.7.7 (GUI) MMP/1.0', '17014-7472-4901-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806'), 1 => array(0 => 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04E')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343944,138369,97064,913, 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04E', '13952-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343944,138369,97064,913, 'Alcatel-OT-806A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13952-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806D'), 1 => array(0 => 'Alcatel-OT-806D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343944,138369,97064,913, 'Alcatel-OT-806D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13952-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806'), 1 => array(0 => 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343944,138369,97064,913, 'Alcatel-OT-806/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13952-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,645789,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '18510-5629-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-799'), 1 => array(0 => 'Alcatel-OT-799/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(379661,138369,97064,913, 'Alcatel-OT-799/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14537-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-799A'), 1 => array(0 => 'Alcatel-OT-799A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(379661,138369,97064,913, 'Alcatel-OT-799A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '14537-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305', 1 => 'OT-305'), 1 => array(0 => 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(216171,138369,98811,913, 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C, Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C', '13564-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305A'), 1 => array(0 => 'Alcatel-OT-305A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(216171,138369,98811,913, 'Alcatel-OT-305A/1.0 ObigoInternetBrowser/Q03C', '13564-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-305'), 1 => array(0 => 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(216171,138369,98811,913, 'Alcatel-OT-305/1.0 ObigoInternetBrowser/Q03C', '13564-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.6.0.318 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,90522,1016432,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.6.0.318 U2/1.0.0 Mobile', '19868-5629-18527-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.6.0.276 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,90522,1016432,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.6.0.276 U2/1.0.0 Mobile', '19868-5629-18527-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807A'), 1 => array(0 => 'Alcatel-OT-807A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,97064,913, 'Alcatel-OT-807A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12548-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807'), 1 => array(0 => 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,97064,913, 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12548-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807'), 1 => array(0 => 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/05S')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,97064,913, 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/05S', '12548-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807'), 1 => array(0 => 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04N')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,97064,913, 'Alcatel-OT-807/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A SVN/04N', '12548-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-807D'), 1 => array(0 => 'Alcatel-OT-807D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,97064,913, 'Alcatel-OT-807D/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12548-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880'), 1 => array(0 => 'Alcatel-OT-880/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(142949,138369,97064,913, 'Alcatel-OT-880/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13391-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880A'), 1 => array(0 => 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(142949,138369,97064,913, 'Alcatel-OT-880A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13391-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-880'), 1 => array(0 => 'Alcatel-OT-880/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(142949,138369,97064,913, 'Alcatel-OT-880/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '13391-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/444')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,124734,303588,913, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/444', '18510-18110-17338-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/355')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,124734,303588,913, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/355', '18510-18110-17338-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/352')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,124734,303588,913, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_918N; 320*480) UCWEB7.9.0.94/139/352', '18510-18110-17338-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.0.1.275 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1390243,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.0.1.275 U2/1.0.0 Mobile', '18510-5629-22261-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.0.2.299 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1390243,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.0.2.299 U2/1.0.0 Mobile', '18510-5629-22261-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,90522,645789,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '19868-5629-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(251085,138369,98811,913, 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13661-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708A'), 1 => array(0 => 'Alcatel-OT-708A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(251085,138369,98811,913, 'Alcatel-OT-708A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13661-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708', 1 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(251085,138369,98811,913, 'Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-708/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13661-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-708'), 1 => array(0 => 'Alcatel-OT-708/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(251085,138369,98811,913, 'Alcatel-OT-708/1.0 model-orange Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13661-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 985N) U2/1.0.0 UCBrowser/9.0.1.275 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,90522,1390243,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 985N) U2/1.0.0 UCBrowser/9.0.1.275 U2/1.0.0 Mobile', '19868-5629-22261-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-807a')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,54471,913, 'alcatel-ot-807a', '12548-7472-17470-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.1.0.297 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1464974,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.1.0.297 U2/1.0.0 Mobile', '18510-5629-22881-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_985N; 320*480) UCWEB7.9.0.94/139/444')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,124734,303588,913, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_985N; 320*480) UCWEB7.9.0.94/139/444', '19868-18110-17338-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_985N; 320*480) UCWEB7.9.0.94/139/355')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,124734,303588,913, 'JUC (Linux; U; 2.3.6; zh-cn; ALCATEL_ONE_TOUCH_985N; 320*480) UCWEB7.9.0.94/139/355', '19868-18110-17338-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-606a')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(201349,138369,54471,913, 'alcatel-ot-606a', '14455-7472-17470-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-806A'), 1 => array(0 => 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(343944,138369,98811,913, 'Alcatel-OT-806A/1.0 ObigoInternetBrowser/Q03C', '13952-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-660'), 1 => array(0 => 'Alcatel-OT-660/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(268057,138369,98811,913, 'Alcatel-OT-660/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12241-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-660A'), 1 => array(0 => 'Alcatel-OT-660A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(268057,138369,98811,913, 'Alcatel-OT-660A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12241-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.7.0.315 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1033046,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_918N) U2/1.0.0 UCBrowser/8.7.0.315 U2/1.0.0 Mobile', '18510-5629-18529-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-505'), 1 => array(0 => 'Alcatel-OT-505/1.0 model-Bouygues ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(315128,138369,98811,913, 'Alcatel-OT-505/1.0 model-Bouygues ObigoInternetBrowser/Q03C', '14333-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-505'), 1 => array(0 => 'Alcatel-OT-505/1.0 version 010 03 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(315128,138369,98811,913, 'Alcatel-OT-505/1.0 version 010 03 ObigoInternetBrowser/Q03C', '14333-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-505'), 1 => array(0 => 'Alcatel-OT-505/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(315128,138369,98811,913, 'Alcatel-OT-505/1.0 ObigoInternetBrowser/Q03C', '14333-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-300'), 1 => array(0 => 'Alcatel-OT-300/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(348342,138369,98811,913, 'Alcatel-OT-300/1.0 ObigoInternetBrowser/Q03C', '14073-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-600'), 1 => array(0 => 'Alcatel-OT-600/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(211232,138369,98811,913, 'Alcatel-OT-600/1.0 ObigoInternetBrowser/Q03C', '15270-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 4.1.1; en-US; ALCATEL_ONE_TOUCH_4030D) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1344949,610861,645789,913, 'UCWEB/2.0 (Linux; U; Adr 4.1.1; en-US; ALCATEL_ONE_TOUCH_4030D) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '21968-18111-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; ALCATEL_ONE_TOUCH_930D) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1283082,576960,645789,913, 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; ALCATEL_ONE_TOUCH_930D) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '21152-18066-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-706'), 1 => array(0 => 'Alcatel-OT-706/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(295307,138369,98811,913, 'Alcatel-OT-706/1.0 ObigoInternetBrowser/Q03C', '12688-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-706A'), 1 => array(0 => 'Alcatel-OT-706A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(295307,138369,98811,913, 'Alcatel-OT-706A/1.0 ObigoInternetBrowser/Q03C', '12688-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 985N) U2/1.0.0 UCBrowser/9.1.0.297 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,90522,1464974,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 985N) U2/1.0.0 UCBrowser/9.1.0.297 U2/1.0.0 Mobile', '19868-5629-22881-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-600A'), 1 => array(0 => 'Alcatel-OT-600A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,98811,913, 'Alcatel-OT-600A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15364-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'GLAMPHONE-ELLE-A'), 1 => array(0 => 'Alcatel-GLAMPHONE-ELLE-A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,98811,913, 'Alcatel-GLAMPHONE-ELLE-A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15364-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S321A'), 1 => array(0 => 'Alcatel-OT-S321A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,98811,913, 'Alcatel-OT-S321A/1.0 ObigoInternetBrowser/Q03C', '15364-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S626A'), 1 => array(0 => 'Alcatel-OT-S626A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,98811,913, 'Alcatel-OT-S626A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15364-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C820'), 1 => array(0 => 'Alcatel-OT-C820/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,98811,913, 'Alcatel-OT-C820/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15364-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-360A'), 1 => array(0 => 'Alcatel-OT-360A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,98811,913, 'Alcatel-OT-360A/1.0 ObigoInternetBrowser/Q03C', '15364-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/010_02 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(156214,138369,98811,913, 'Alcatel-OT-363/010_02 ObigoInternetBrowser/Q03C', '13629-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363A'), 1 => array(0 => 'Alcatel-OT-363A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(156214,138369,98811,913, 'Alcatel-OT-363A/1.0 ObigoInternetBrowser/Q03C', '13629-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(156214,138369,98811,913, 'Alcatel-OT-363/1.0 model-orange ObigoInternetBrowser/Q03C', '13629-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-363'), 1 => array(0 => 'Alcatel-OT-363/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(156214,138369,98811,913, 'Alcatel-OT-363/1.0 ObigoInternetBrowser/Q03C', '13629-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.7.0.315 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(996304,90522,1033046,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_985N) U2/1.0.0 UCBrowser/8.7.0.315 U2/1.0.0 Mobile', '19868-5629-18529-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S319'), 1 => array(0 => 'Alcatel-OT-S319/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(269120,138369,98811,913, 'Alcatel-OT-S319/1.0 model-orange ObigoInternetBrowser/Q03C', '12288-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S319'), 1 => array(0 => 'Alcatel-OT-S319/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(269120,138369,98811,913, 'Alcatel-OT-S319/1.0 ObigoInternetBrowser/Q03C', '12288-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'Mozilla/5.0 (Java; U; es-la; alcatel-ot-807a) AppleWebKit/530.13 (KHTML, like Gecko) UCBrowser/8.5.0.185/82/352/UCWEB Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,949240,913, 'Mozilla/5.0 (Java; U; es-la; alcatel-ot-807a) AppleWebKit/530.13 (KHTML, like Gecko) UCBrowser/8.5.0.185/82/352/UCWEB Mobile', '12548-7472-18520-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.2.0.308 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(860970,90522,1510306,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL ONE TOUCH 918N) U2/1.0.0 UCBrowser/9.2.0.308 U2/1.0.0 Mobile', '18510-5629-24055-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_916) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1011085,90522,645789,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_916) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '20019-5629-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-303A'), 1 => array(0 => 'Alcatel-OT-303A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199954,138369,98811,913, 'Alcatel-OT-303A/1.0 ObigoInternetBrowser/Q03C', '13899-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-303'), 1 => array(0 => 'Alcatel-OT-303/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199954,138369,98811,913, 'Alcatel-OT-303/1.0 ObigoInternetBrowser/Q03C', '13899-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_903) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(1091915,90522,645789,913, 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; ALCATEL_ONE_TOUCH_903) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile', '19857-5629-18326-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C701A'), 1 => array(0 => 'Alcatel-OT-C701A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199666,138369,98811,913, 'Alcatel-OT-C701A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15741-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C701'), 1 => array(0 => 'Alcatel-OT-C701/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199666,138369,98811,913, 'Alcatel-OT-C701/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15741-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-508A'), 1 => array(0 => 'Alcatel-OT-508A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(382613,138369,98811,913, 'Alcatel-OT-508A/1.0 ObigoInternetBrowser/Q03C', '14683-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => NULL, 1 => array(0 => 'alcatel-ot-807a/UC Browser7.0.0.41/69/4255')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(219727,138369,32691,913, 'alcatel-ot-807a/UC Browser7.0.0.41/69/4255', '12548-7472-4722-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S621'), 1 => array(0 => 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(230227,138369,98811,913, 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15503-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S621', 1 => 'OT-S621'), 1 => array(0 => 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(230227,138369,98811,913, 'Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C, Alcatel-OT-S621/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15503-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S621A'), 1 => array(0 => 'Alcatel-OT-S621A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(230227,138369,98811,913, 'Alcatel-OT-S621A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15503-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'TH3'), 1 => array(0 => 'Alcatel-TH3/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(211080,138369,12619,913, 'Alcatel-TH3/1.0 UP.Browser/6.2.ALCATEL MMP/1.0', '15266-7472-3625-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-v770'), 1 => array(0 => 'Alcatel-OT-v770/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(226693,138369,98811,913, 'Alcatel-OT-v770/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15454-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'TH4'), 1 => array(0 => 'Alcatel-TH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(44218,138369,12619,913, 'Alcatel-TH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0', '15364-7472-3625-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S520'), 1 => array(0 => 'Alcatel-OT-S520/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(328134,138369,98811,913, 'Alcatel-OT-S520/1.0 ObigoInternetBrowser/Q03C', '13010-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S520A'), 1 => array(0 => 'Alcatel-OT-S520A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(328134,138369,98811,913, 'Alcatel-OT-S520A/1.0 ObigoInternetBrowser/Q03C', '13010-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S320'), 1 => array(0 => 'Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(382757,138369,98811,913, 'Alcatel-OT-S320/1.0 ObigoInternetBrowser/Q03C', '14688-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S320'), 1 => array(0 => 'Alcatel-OT-S320/1.0 model-orange ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(382757,138369,98811,913, 'Alcatel-OT-S320/1.0 model-orange ObigoInternetBrowser/Q03C', '14688-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BH4'), 1 => array(0 => 'Alcatel-BH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(351661,138369,12619,913, 'Alcatel-BH4/1.0 UP.Browser/6.2.ALCATEL MMP/1.0', '17018-7472-3625-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-565A'), 1 => array(0 => 'Alcatel-OT-565A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199522,138369,98811,913, 'Alcatel-OT-565A/1.0 ObigoInternetBrowser/Q03C', '15078-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V670A'), 1 => array(0 => 'Alcatel-OT-V670A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(291932,138369,98811,913, 'Alcatel-OT-V670A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13075-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V670'), 1 => array(0 => 'Alcatel-OT-V670/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(291932,138369,98811,913, 'Alcatel-OT-V670/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13075-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-I650'), 1 => array(0 => 'Alcatel-OT-I650/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(349286,138369,98811,913, 'Alcatel-OT-I650/1.0 ObigoInternetBrowser/Q03C', '14126-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'MISS-SIXTY-MSX-10'), 1 => array(0 => 'Alcatel-MISS-SIXTY-MSX-10/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(365435,138369,97064,913, 'Alcatel-MISS-SIXTY-MSX-10/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q05A', '12631-7472-3534-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-315M'), 1 => array(0 => 'Alcatel-OT-315M/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(377717,138369,98811,913, 'Alcatel-OT-315M/1.0 ObigoInternetBrowser/Q03C', '14494-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S853'), 1 => array(0 => 'Alcatel-OT-S853/1.0 UP.Browser/7.1 (GUI) MMP/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(216891,138369,63018,913, 'Alcatel-OT-S853/1.0 UP.Browser/7.1 (GUI) MMP/2.0', '15330-7472-4893-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C700A'), 1 => array(0 => 'Alcatel-OT-C700A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(327126,138369,98811,913, 'Alcatel-OT-C700A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12988-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C700'), 1 => array(0 => 'Alcatel-OT-C700/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(327126,138369,98811,913, 'Alcatel-OT-C700/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12988-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Mandarina-Duck'), 1 => array(0 => 'Alcatel-Mandarina-Duck/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(215884,138369,98811,913, 'Alcatel-Mandarina-Duck/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15317-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C707'), 1 => array(0 => 'Alcatel-OT-C707/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(226333,138369,98811,913, 'Alcatel-OT-C707/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15445-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-216'), 1 => array(0 => 'Alcatel-OT-216/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323343,138369,98811,913, 'Alcatel-OT-216/1.0 ObigoInternetBrowser/Q03C', '12951-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'MissSixty'), 1 => array(0 => 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(365435,138369,98811,913, 'Alcatel-MissSixty/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12631-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'BG3'), 1 => array(0 => 'Alcatel-BG3/1.0 UP.Browser/5.0.3.1.2')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(416943,138369,52405,913, 'Alcatel-BG3/1.0 UP.Browser/5.0.3.1.2', '15515-7472-4948-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C630'), 1 => array(0 => 'Alcatel-OT-C630/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(417013,138369,98811,913, 'Alcatel-OT-C630/1.0 ObigoInternetBrowser/Q03C', '17344-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C550'), 1 => array(0 => 'Alcatel-OT-C550/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(247848,138369,98811,913, 'Alcatel-OT-C550/1.0 ObigoInternetBrowser/Q03C', '15664-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Crystal'), 1 => array(0 => 'Alcatel-Crystal/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(288517,138369,98811,913, 'Alcatel-Crystal/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12823-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-383A'), 1 => array(0 => 'Alcatel-OT-383A/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(363275,138369,98811,913, 'Alcatel-OT-383A/1.0 ObigoInternetBrowser/Q03C', '12569-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C717'), 1 => array(0 => 'Alcatel-OT-C717/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(239266,138369,98811,913, 'Alcatel-OT-C717/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '15573-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-C552'), 1 => array(0 => 'Alcatel-OT-C552/1.0 UP.Browser/7.1 (GUI) MMP/2.0')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(246044,138369,63018,913, 'Alcatel-OT-C552/1.0 UP.Browser/7.1 (GUI) MMP/2.0', '15637-7472-4893-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-V570A'), 1 => array(0 => 'Alcatel-OT-V570A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(323199,138369,98811,913, 'Alcatel-OT-V570A/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12946-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S920'), 1 => array(0 => 'Alcatel-OT-S920/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q04A')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(328350,138369,69743,913, 'Alcatel-OT-S920/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q04A', '13017-7472-4203-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'Mandarina-Duck-MOON'), 1 => array(0 => 'Alcatel-Mandarina-Duck-MOON/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(331376,138369,98811,913, 'Alcatel-Mandarina-Duck-MOON/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '13084-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-S218'), 1 => array(0 => 'Alcatel-OT-S218/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(363059,138369,98811,913, 'Alcatel-OT-S218/1.0 ObigoInternetBrowser/Q03C', '12556-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'ELLE-N3'), 1 => array(0 => 'Alcatel-ELLE-N3/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(364355,138369,98811,913, 'Alcatel-ELLE-N3/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1 ObigoInternetBrowser/Q03C', '12591-7472-3807-18092');
    $ls = $ns;
  }
  $ns = E0($segments, array(0 => array(0 => 'OT-280'), 1 => array(0 => 'Alcatel-OT-280/1.0 ObigoInternetBrowser/Q03C')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(450960,138369,98811,913, 'Alcatel-OT-280/1.0 ObigoInternetBrowser/Q03C', '15519-7472-3807-18092');
    $ls = $ns;
  }
  return $dl;
}
