<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0.
 *
 * If a copy of the MPL was not distributed with this file, You can obtain one
 * at http://mozilla.org/MPL/2.0/.
 *
 * This Source Code Form is "Incompatible With Secondary Licenses", as defined
 * by the Mozilla Public License, v. 2.0.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The edit distance between the two strings.
 */
function E39($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H39($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'FLY-MX230/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'FLY-MX330/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX300/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1 FLY-SX300/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX310/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-SX100/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'FLY-MX300/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'FLY-SL399e/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly MC100/S120 Release/2008.02.26 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-LX610/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-SX200/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-LX600/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'FLY M130 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-SX315/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-E105/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly-DS500/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,15136,6, $ua);
  }
  $ua = 'Fly_E190 Wi-Fi    Opera/9.80 (MTK; Nucleus; U; ru-RU) Presto/2.4.18 Version/10.00';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,221066,6, $ua);
  }
  $ua = 'FLY-MP500/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,20180,6, $ua);
  }
  $ua = 'FLY-MX200i/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,20180,6, $ua);
  }
  $ua = 'FLY-SL500m/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,20180,6, $ua);
  }
  $ua = 'FLY-SL300m/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,20180,6, $ua);
  }
  $ua = 'FLY-SX205/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(21187,20173,20180,6, $ua);
  }
  $ua = 'Fly DS160, Fly DS160';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(75581,20173,15136,6, $ua);
  }
  $ua = 'Fly DS160';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(75581,20173,15136,6, $ua);
  }
  $ua = 'Fly_DS160/Configuration/WapBrowser2.0 Novarra-Vision/8.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(75581,20173,15136,6, $ua);
  }
  $ua = 'Fly_DS170 Configuration/WAP2.0/Browser';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(75581,20173,15136,6, $ua);
  }
  $ua = 'Fly_E135/MAUIBrowser/Configuration/WAP2.0 Novarra-Vision/8.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(216739,20173,212214,6, $ua);
  }
  $ua = 'Fly_E135/MAUIBrowser/Configuration/WAP2.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(216739,20173,212214,6, $ua);
  }
  $ua = 'Fly_Q400/WapBrowserprofile/WIFIprofile/MIDP2.0Configuration/CLDC1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(248777,20173,15136,6, $ua);
  }
  $ua = 'Fly_E140_India/WAPBrowser2.0Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(315641,20173,15136,6, $ua);
  }
  $ua = 'Fly_E140/WAPBrowser2.0Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(315641,20173,15136,6, $ua);
  }
  $ua = 'Fly_E140/WAPBrowser2.0Profile/MIDP-2.0 Configuration/CLDC-1.1, Fly_E140/WAPBrowser2.0Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(315641,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX210/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(163159,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX210/Profile/MIDP.2.0Configuration/CLDC.1.0, FLY-SX210/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(163159,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX210/Profile/MIDP.2.0Configuration/CLDC.1.0 FLY-SX210/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(163159,20173,15136,6, $ua);
  }
  $ua = 'Fly_DS150/MAUIBrowser/Configuration/WAP2.0, Fly_DS150/MAUIBrowser/Configuration/WAP2.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(329433,20173,212214,6, $ua);
  }
  $ua = 'Fly_DS150/MAUIBrowser/Configuration/WAP2.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(329433,20173,212214,6, $ua);
  }
  $ua = 'Fly_DS100/WAP2.0Configuration/Browser';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(343169,20173,15136,6, $ua);
  }
  $ua = 'FLY-SL600/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(345761,20173,20180,6, $ua);
  }
  $ua = 'FLY-SL600/BSI AU.Browser/2.0 QO3C1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(345761,20173,20180,6, $ua);
  }
  $ua = 'FLY_SL400m/(06.11.27)Ver01.06/WAP2.0, FLY_SL400m/(06.11.27)Ver01.06/WAP2.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(86955,20173,15136,6, $ua);
  }
  $ua = 'FLY_SL400m/(07.05.14)Ver00.06/WAP2.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(86955,20173,15136,6, $ua);
  }
  $ua = 'Fly-E300/Profile/MIDP.2.0Configuration/CLDC.1.0, Fly-E300/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(225537,20173,15136,6, $ua);
  }
  $ua = 'Fly-E300/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(225537,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX390/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1, FLY-SX390/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(229707,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX390/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(229707,20173,15136,6, $ua);
  }
  $ua = 'FLY-2040L/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(343961,20173,20180,6, $ua);
  }
  $ua = 'FLY-2040i/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(343961,20173,20180,6, $ua);
  }
  $ua = 'Fly_DS185/WAP2.0Configuration/Browser';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(180903,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX305/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1, FLY-SX305/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(235054,20173,15136,6, $ua);
  }
  $ua = 'FLY-SX305/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(235054,20173,15136,6, $ua);
  }
  $ua = 'Fly-HT2_i08 ObigoInternetBrowser/QO3C Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(369416,20173,15136,6, $ua);
  }
  $ua = 'Fly V180 DS/2.0 (5.0614.0) SymbianOS/7.0s Series60/2.1 Profile/MIDP-2.0Configuration/CLDC-1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(165031,30509,30587,6, $ua);
  }
  $ua = 'Fly-SX225/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(257545,20173,15136,6, $ua);
  }
  $ua = 'Fly_DS210 ObigoInternetBrowser/QO3C Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(313984,20173,15136,6, $ua);
  }
  $ua = 'Fly_MC150ds/WAP2.0Configuration/Browser';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(324602,20173,15136,6, $ua);
  }
  $ua = 'Fly-B400/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(334341,20173,15136,6, $ua);
  }
  $ua = 'FLY-SL500i/BSI AU.Browser/2.0 QO3C1 MMP/1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(345689,20173,20180,6, $ua);
  }
  $ua = 'Fly-V130/Profile/MIDP.2.0Configuration/CLDC.1.0';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(346193,20173,15136,6, $ua);
  }
  $ua = 'Fly_2040';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(343961,20173,15136,6, $ua);
  }
  $ua = 'FLY-2040/2.0 (03.15) Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(343961,20173,15136,6, $ua);
  }
  $ua = 'FLY B700 WAP Browser';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(429190,20173,15136,6, $ua);
  }
  $ua = 'FLY-SL600';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(345761,20173,15136,6, $ua);
  }
  $ua = 'Fly_SL500i';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(345689,20173,15136,6, $ua);
  }
  $ua = 'Fly SX240/Teleca/Q03C1.22 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E39($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(422602,20173,112938,6, $ua);
  }
  return $dl;
}
