<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the matching score between the two strings for this handler.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The score between the two strings.
 */
function E61($target, $test, $ls) {
  $score = 0;
  fiftyone_degrees_calculate_segment_score($target[0], $test[0], $ls, 10000, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[1], $test[1], $ls, 10, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[2], $test[2], $ls, 5, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  fiftyone_degrees_calculate_segment_score($target[3], $test[3], $ls, 5, $score);
  if ($score == PHP_INT_MAX) {
    return PHP_INT_MAX;
  }
  return $score;
}

/**
 * Returns the details of the devices that are closest to the
 * useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H61($useragent) {

  $ls = PHP_INT_MAX;
  $dl = array();

  // Calculate the segments for the useragent.
  $segments = array(
    0 => fiftyone_degrees_preg_match_all('#(?<=Opera/)[\\d+.]+|(?<=Opera )[\\d\\.]+#', $useragent),
    1 => fiftyone_degrees_preg_match_all('#(?<=\\()[^;]+#', $useragent),
    2 => fiftyone_degrees_preg_match_all('#(?<=Presto/)\\d+\\.\\d+#', $useragent),
    3 => fiftyone_degrees_preg_match_all('#(?<=Version/)\\d+\\.\\d+#', $useragent));
  $ns = E61($segments, array(0 => array(0 => '11.62'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,606577,6, 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; en) Opera 11.62');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '11.61'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,584486,6, 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; en) Opera 11.61');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '11.61'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,584486,6, 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; en) Opera 11.61');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '11.62'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,606577,6, 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; en) Opera 11.62');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.00'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.00');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; ru) Opera 8.01');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.01'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/5.0 (Windows NT 5.1; U; en) Opera 8.01');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.00'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/5.0 (Windows NT 5.1; U; en) Opera 8.00');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.02');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0', 1 => '8.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 8.0	Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.02'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/5.0 (Windows NT 5.1; U; en) Opera 8.02');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,311796,6, 'Mozilla/5.0 (Windows NT 5.1; U; en) Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.54 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.1) Opera 7.01 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.50  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.60'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 7.60');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.60'), 1 => array(0 => 'compatible', 1 => 'IBM EVV/3.0/EAK01AG9/LE)'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.60  [en] (IBM EVV/3.0/EAK01AG9/LE)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.1) Opera 7.02 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.20'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.20 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.10'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.10 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.51'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.51 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows XP) Opera 7.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/5.0 (Windows NT 5.1; U) Opera 7.54 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.03'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.1) Opera 7.03 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.04'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.1) Opera 7.04 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.23'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.23 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.11 [ru]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.21'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.21  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.52'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.52 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.53'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1) Opera 7.53 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.21'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; de) Opera 9.21');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.24'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.24');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.27'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; en) Opera 9.27');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.26'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.26');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.22'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.22');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.23'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; MEGAUPLOAD 1.0; ru) Opera 9.23');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.64'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,145614,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.64');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.63'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,145614,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.63');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.50'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,129513,6, 'Opera/9.50 (Windows NT 5.1; MDA_Compact_V/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.52'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,129513,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; ru) Opera 9.52');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,129513,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; en) Opera 9.50');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.51'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,129513,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; ru) Opera 9.51');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,448119,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '11.61'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,67164,584486,6, 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; en) Opera 11.61');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '10.51'), 1 => array(0 => 'Linux i686'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,199667,6, 'Mozilla/5.0 (Linux i686; U; en; rv:1.9.1.6) Gecko/X Firefox/3.5.6 Opera 10.51');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80'), 1 => array(0 => 'Windows NT 5.1'), 2 => array(0 => '2.2'), 3 => array(0 => '10.10')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,497327,6, '"Opera/9.80 (Windows NT 5.1; U; en) Presto/2.2.15 Version/10.10"');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.26'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,67164,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.0; en) Opera 9.26');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.02 Bork-edition [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.01'), 1 => array(0 => 'Windows NT 5.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/5.0 (Windows NT 5.0; U) Opera 7.01 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.11'), 1 => array(0 => 'Windows NT 5.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/5.0 (Windows NT 5.0; U) Opera 7.11 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.23'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0) Opera 7.23 [ca]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.21'), 1 => array(0 => 'Windows NT 5.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/5.0 (Windows NT 5.0; U) Opera 7.21 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0) Opera 7.11 [fr]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.01 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.10'), 1 => array(0 => 'Windows NT 5.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/3.0 (Windows NT 5.0; U) Opera 7.10 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.03'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 5.0) Opera 7.03 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0) Opera 7.50 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'Windows NT 5.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/5.0 (Windows NT 5.0; U) Opera 7.50');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0) Opera 7.54u1');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.64'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,145614,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.1; YB/3.5.1; ru) Opera 9.64');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.70'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,51124,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Linux i686 ; en) Opera 9.70');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.70'), 1 => array(0 => 'Linux i686 '), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,51124,6, 'Mozilla/5.0 (Linux i686 ; U; en; rv:1.8.1) Gecko/X Firefox/2.0.0 Opera 9.70');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows NT 4.0) Opera 7.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.23'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 4.0) Opera 7.23 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 4.0) Opera 7.11 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.27'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686; en) Opera 9.27');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.22'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686; en) Opera 9.22');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.60'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,145614,6, 'Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux x86_64; en) Opera 9.60');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,383259,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) Opera 6.01  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,383259,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 95) Opera 6.02 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,16329,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows ME) Opera 7.11  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.5'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,67164,129513,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.0; en) Opera 9.5');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,67164,129513,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.0; en) Opera 9.50');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.70', 1 => '9.70'), 1 => array(0 => 'Windows NT 5.1', 1 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,51124,6, 'CS-HTTPRequest_Opera/9.70 (Windows NT 5.1; U; en) TMO-US_LEO, Opera/9.70 (Windows NT 5.1; U; en) TMO-US_LEO');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => array(0 => 'Windows NT 5.2'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,51124,6, 'Opera 9.7 (Windows NT 5.2; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.01'), 1 => array(0 => 'Windows XP'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/5.0 (Windows XP; U) Opera 6.01 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.05'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows XP) Opera 6.05 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.06'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows XP) Opera 6.06 [fr]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.06'), 1 => array(0 => 'Windows XP'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/5.0 (Windows XP; U) Opera 6.06 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows XP) Opera 6.01  [ru]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows XP) Opera 6.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.04'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows XP) Opera 6.04 [fr]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80'), 1 => array(0 => 'MTK'), 2 => array(0 => '2.5'), 3 => array(0 => '10.10')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,167488,6, 'ASTRO36_TD/v3 MAUI/10A1032MP_ASTRO_W1052 Release/31.12.2010 Browser/Opera Profile/MIDP-2.0 Configuration/CLDC-1.1 Sync/SyncClient1.1 Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '10.00'), 1 => array(0 => 'Windows 98'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,245270,6, 'Mozilla/4.0 (Windows 98; US) Opera 10.00 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.21'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98) Opera 7.21  [pt-BR]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows 98) Opera 7.02 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.20'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98) Opera 7.20 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98) Opera 7.54');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.03'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows 98) Opera 7.03 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98) Opera 7.50 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.55'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98) Opera 7.55');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; MSIE 5.5; Windows 98) Opera 7.01 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.23'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98) Opera 7.23 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; en) Opera 8.01');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; en) Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; de) Opera 8.02');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; ; Linux i686) Opera 7.50 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.11'), 1 => array(0 => 'Linux 2.4.21-0.13mdk i686'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/5.0 (Linux 2.4.21-0.13mdk i686; U) Opera 7.11 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686) Opera 7.54 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'X11'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/5.0 (X11; Linux i686; U) Opera 7.54 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.60'), 1 => array(0 => 'X11'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/5.0 (X11; Linux i386; U) Opera 7.60  [en-GB]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'X11'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/5.0 (X11; Linux i686; U) Opera 7.50  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.23'), 1 => array(0 => 'MSIE 6.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'MSIE (MSIE 6.0; X11; Linux; i686) Opera 7.23');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.23'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686) Opera 7.23');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.01 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.04'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.04 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.05'), 1 => array(0 => 'Windows NT 4.0'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,461660,6, 'Mozilla/5.0 (Windows NT 4.0; U) Opera 6.05 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.0 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 6.02 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.12'), 1 => array(0 => 'Windows 98'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,447184,6, 'Mozilla/4.76 (Windows 98; U) Opera 5.12 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,447184,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 5.02 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.12'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,447184,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 5.12 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,447184,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 5.11  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.64'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,68106,145614,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; de) Opera 9.64');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.12'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,478311,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Linux 2.4.20-4GB i686) Opera 6.12 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,478311,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Linux 2.4.4 i686) Opera 6.11 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Linux 2.4.18-rmk7-pxa3-embedix armv5tel; 480x640) Opera 6.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.03'), 1 => array(0 => 'Linux 2.4.18-18.7.x i686'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,461660,6, 'Mozilla/5.0 (Linux 2.4.18-18.7.x i686; U) Opera 6.03 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.03'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Linux 2.4.20-4GB i686) Opera 6.03 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; de) Opera 8.02');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; en) Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.01'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 6.01  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.03'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 6.03 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 6.0 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.04'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,258919,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows 98) Opera 6.04');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686; en) Opera 8.02');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(36506,16329,45126,6, 'Smartphone  Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; Smartphone; 240x320) Opera 8.65');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,45126,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) Opera 8.65 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.60'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,45126,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) Opera 8.60 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.02'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(61820,146452,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Mac_PowerPC Mac OS X; en) Opera 8.02');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0'), 1 => array(0 => 'Macintosh'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(61820,146452,311796,6, 'Mozilla/5.0 (Macintosh; PPC Mac OS X; U; en) Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(131445,46332,51153,6, 'HD_mini_T5555 Opera/9.7 (Windows NT 5.1; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,145607,447184,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Linux) Opera 5.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80'), 1 => array(0 => 'MTK'), 2 => array(0 => '2.4'), 3 => array(0 => '10.00')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,245270,6, 'TecomM500 1.0 20110421 1.0  Opera/9.80 (MTK; Nucleus; U; zh-TW) Presto/2.4.18 Version/10.00');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,16329,45126,6, 'htc-cleo/Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; Smartphone; 320x240) Opera 8.65 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.4'), 1 => array(0 => 'Windows NT 6.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,542006,6, 'Opera 9.4 (Windows NT 6.1; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.4', 1 => '9.4'), 1 => array(0 => 'Windows NT 6.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,542006,6, 'Opera 9.4 (Windows NT 6.1; U; en)	Opera 9.4');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.0'), 1 => array(0 => 'SunOS 5.8 sun4u'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,521640,447184,6, 'Mozilla/5.0 (SunOS 5.8 sun4u; U) Opera 5.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => NULL, 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(170635,7696,6759,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Windows Phone 6.5) garmin-asus-Nuvifone-M10/1.0 Opera9.5');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80'), 1 => array(0 => 'MTK'), 2 => array(0 => '2.5'), 3 => array(0 => '10.10')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,497327,6, 'Browser/Opera  Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.4'), 1 => array(0 => 'Windows NT 5.3'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,306950,542006,6, 'Opera 9.4 (Windows NT 5.3; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,447184,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Mac_PowerPC) Opera 5.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,461660,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Mac_PowerPC) Opera 6.0 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.70'), 1 => array(0 => 'Windows NT  5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,7696,51124,6, 'XV6875.1 Opera/9.70 (Windows NT  5.1; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.24'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,422977,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Mac_PowerPC; en) Opera 9.24');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80'), 1 => array(0 => 'J2ME/MIDP)'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,361045,6, 'Opera/9.80 (J2ME/MIDP)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,478311,6, 'Mozilla/4.0 (compatible; MSIE 5.0; UNIX) Opera 6.11 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80'), 1 => array(0 => 'MTK'), 2 => array(0 => '2.5'), 3 => array(0 => '10.10')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(226654,20547,167488,6, 'MicromaxX640ASTRO36_TD/v3 MAUI/10A1032MP_ASTRO_W1052 Release/31.12.2010 Browser/Opera Profile/MIDP-2.0 Configuration/CLDC-1.1 Sync/SyncClient1.1 Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.50'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(120794,46332,129513,6, 'Opera/9.50 (Windows NT 5.1; MDA_Vario_V/1.1 Profile/MIDP-2.0 Configuration/CLDC-1.1; U; de)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(96861,45028,45126,6, 'MOTORIZR-Z8/46.00.00 Mozilla/4.0 (compatible; MSIE 6.0; Symbian OS; 381) Opera 8.65 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '5.11'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,379463,447184,6, 'Mozilla/4.0 (compatible; MSIE 5.0; Windows NT 4.0) Opera 5.11 [de]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.50'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.1) Opera 7.50  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,67171,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.1) Opera 7.54  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.2'), 1 => array(0 => 'WILLCOM'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,67171,6, 'Mozilla/3.0(WILLCOM;KYOCERA/WX330K/2;2.0.8.28.000000/0.1/C100) Opera 7.2 EX');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '7.54'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,67171,6, 'Mozilla/4.0 (compatible; MSIE 5.23; Mac_PowerPC) Opera 7.54  [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,118535,311796,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 6.1; en) Opera 8.0');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(196227,45028,45126,6, 'MOTO-Z10/50.00.00 Mozilla/4.0 (compatible; MSIE 6.0; Symbian OS; 335) Opera 8.65 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '4.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,604427,6, 'Mozilla/4.0 (compatible; Opera 4.0)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,45028,45126,6, 'Mozilla/4.0 (compatible; MSIE 6.0; Symbian OS; Series 60/4.0812.4.2.1; 9730) Opera 8.65 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.50'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(181799,46332,129513,6, 'Opera/9.50 (Windows NT 5.1; MDA_compact_IV/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => NULL, 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,51124,6, 'Mozilla/5.0 (; U; ; rv:1.8.1) Gecko/20061208 Firefox/2.0.0 Opera 9.7');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,51124,6, 'Mozilla/4.0 (compatible; MSIE 6.0; ; ) Opera 9.7');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(199402,7696,51153,6, 'dopodT8588/1.0 WindowsMobile/6.5 CEOS/5.2 release/5.0 Opera/9.7 WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1 4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 8.12; MSIEMobile 6.0)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.10'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(168424,45028,478311,6, 'Mozilla/4.1 (compatible; MSIE 5.0; Symbian OS; Series 60;424) Opera 6.10 [en]');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,7696,51153,6, 'dopodT3333/1.0 WindowsMobile/6.5 CEOS/5.2 release/5.0 Opera/9.7 WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1 Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 8.12; MSIEMobile 6.0)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '8.65'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(318028,16329,45126,6, 'ASUS1210/V4.2.4 Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; Smartphone; 240x320; ASUS1210) Opera 8.65');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '6.0'), 1 => array(0 => 'compatible'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,45028,461660,6, 'Mozilla/4.1 (compatible; MSIE 5.0; Symbian OS) Opera 6.0 [en]./MOT-A920./P325');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.7'), 1 => array(0 => 'Windows NT 5.1'), 2 => NULL, 3 => NULL), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,46332,51153,6, 'D_mini_T5555 Opera/9.7 (Windows NT 5.1; U; en)');
    $ls = $ns;
  }
  $ns = E61($segments, array(0 => array(0 => '9.80+'), 1 => array(0 => 'J2ME/MIDP'), 2 => array(0 => '2.8'), 3 => array(0 => '11.10')), $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
    }
    $dl[] = array(20443,20547,625997,6, 'Opera/9.80+(J2ME/MIDP;+Opera+Mini/7.0.30088/28.2075;+U;+en)+Presto/2.8.119+Version/11.10');
    $ls = $ns;
  }
  return $dl;
}
