<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The edit distance between the two strings.
 */
function E69($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H69($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'portalmmm/2.0 S500i(c20;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478135,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 LG342i(c10;TJ)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(20443,5630,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 LG342i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(20443,5630,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 LG342i(c30;TD)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(20443,5630,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S400i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477873,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S400i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477873,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S400i(c10,TJ)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477873,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S400i(c100,TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477873,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S400i(c10;TC)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477873,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 K550im(c100;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(262394,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 K550im(c100;TJ)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(262394,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 K550im(c20;TD)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(262394,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 K550im(c100;TC)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(262394,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z320i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477263,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z320i(c100;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477263,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z320i(c30;TD)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477263,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z320i(c10;TJ)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477263,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S410i(c10;TC)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478048,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S410i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478048,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S410i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478048,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S410i(c10;TJ)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478048,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S410i(c30;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478048,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z650i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477176,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z650i(c20;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477176,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z650i(c100;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477176,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 Z650i(c300;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477176,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S342i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477089,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S342i(c30;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477089,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S342i(c100;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477089,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S401i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477961,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S501i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478224,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S501i(c20;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(478224,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG342i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477525,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG342i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477525,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG321i (c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477351,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG321i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477351,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG321i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477351,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 my401Ci';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464326,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 my401Ci(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464326,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S720i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464760,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S720i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464760,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S730i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464847,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 S730i(c20;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464847,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG341i (c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477438,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG346i';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477786,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG346i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477786,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG345i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(464501,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG321i (c10;TB) Profile/DoCoMoProfile-1.5oe Configuration/CLDC-1.0 UP.Browser/7.0.0.1.102 (GUI)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477351,309889,64260,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG343i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477612,20547,16335,6, $ua);
  }
  $ua = 'portalmmm/2.0 SG344i(c10;TB)';
  $ns = E69($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(477699,20547,16335,6, $ua);
  }
  return $dl;
}
