<?php
/**
 * @file
 * Auto Generated Code - DO NOT EDIT
 *
 * See http://51degrees.mobi/Support/Documentation/PHP#AutoGeneratedSourceCode for more details.*
 */

/**
 * See LICENSE.TXT for terms of use and copyright.
 */

/**
 * Calculates the edit distance between the two strings.
 *
 * &$target string
 *   The string we're trying to find the closest value to.
 * $test string
 *   The string that we're testing against.
 * $ls integer
 *   The lowest score we've found so far.
 * return integer
 *   The edit distance between the two strings.
 */
function E90($target, $test, $ls) {
  return fiftyone_degrees_edit_distance($target, $test, $ls);
}

/**
 * Returns the details of the devices that are closest to the useragent string provided.
 *
 * $useragent string
 *   The useragent we're trying to find.
 * return array
 *   An array of device details for the closest devices.
 */
function _H90($useragent) {
  $ls = PHP_INT_MAX;
  $dl = array();
  $ua = 'Spice M6688 MAUI/10A1032MP_ASTRO_W1052 Release/31.12.2010 Browser/Opera Profile/MIDP-2.0 Configuration/CLDC-1.1 Sync/SyncClient1.1 Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(28561,321377,143957,913, $ua, '18088-22857-18373-18092');
  }
  $ua = 'Browser/Opera Spice M6868n Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,321377,143957,913, $ua, '15364-22857-18373-18092');
  }
  $ua = 'Browser/Opera Spice M6868n Opera/9.80 (MTK; Nucleus; Opera Mobi/4000; U; hi-IN) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,321377,143957,913, $ua, '15364-22857-18373-18092');
  }
  $ua = 'Spice M5100';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice QT53';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M-5180';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5460';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M6450';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5456';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M-5455';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5225';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5665';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5560';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice_M-5400/WapBrowserProfile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5670';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M5800';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice QT59';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'Spice M6430';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,54471,913, $ua, '15364-22835-17470-18092');
  }
  $ua = 'SpiceM5600/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1077998,75615,54471,913, $ua, '20247-22835-17470-18092');
  }
  $ua = 'Spice M5600';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1077998,75615,54471,913, $ua, '20247-22835-17470-18092');
  }
  $ua = 'Spice M5600n';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1077998,75615,54471,913, $ua, '20247-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.4; en-US; Spice_Mi280) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,90522,645789,913, $ua, '15364-5629-18326-18092');
  }
  $ua = 'Spice M5885   Browser/Opera  Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,451176,913, $ua, '15364-22835-18272-18092');
  }
  $ua = 'Spice M5885   Browser/Opera  Opera/9.80 (MTK; U; hi-IN) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,451176,913, $ua, '15364-22835-18272-18092');
  }
  $ua = 'Spice M5885 Browser/Opera Opera/9.80 (MTK; U; en-US) Presto/2.5.28 Version/10.10';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,75615,451176,913, $ua, '15364-22835-18272-18092');
  }
  $ua = 'Spice M6800 Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(326982,321377,326027,913, $ua, '12715-22857-4812-18092');
  }
  $ua = 'Spice M6800  Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(326982,321377,326027,913, $ua, '12715-22857-4812-18092');
  }
  $ua = 'Spice M6900 Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(403060,321377,326027,913, $ua, '16696-22857-4812-18092');
  }
  $ua = 'Spice M6900  Opera/9.80 (MTK; Nucleus; U; en-US) Presto/2.4.18 Version/10.00';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(403060,321377,326027,913, $ua, '16696-22857-4812-18092');
  }
  $ua = 'Spice_M-5900/WapBrowserProfile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1158176,75615,54471,913, $ua, '23087-22835-17470-18092');
  }
  $ua = 'Spice M6700';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(785782,75615,54471,913, $ua, '16725-22835-17470-18092');
  }
  $ua = 'Spice M5445';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(294371,75615,54471,913, $ua, '16858-22835-17470-18092');
  }
  $ua = 'SpiceM5365/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1209183,75615,54471,913, $ua, '23020-22835-17470-18092');
  }
  $ua = 'Spice M5364';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1479329,75615,54471,913, $ua, '23332-22835-17470-18092');
  }
  $ua = 'Spice M5910';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1290160,75615,54471,913, $ua, '23572-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.07.09 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.09.26 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.05.29 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.05.16 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.03.03 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.05.31 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.04.28 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.09.02 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.04.10 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.08.20 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.07.15 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.06.29 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.09.27 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2008.12.03 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice S707/2009.03.25 LMP/SH Release Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(138591,75615,54471,913, $ua, '16862-22835-17470-18092');
  }
  $ua = 'Spice M5385';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1479257,75615,54471,913, $ua, '23333-22835-17470-18092');
  }
  $ua = 'SpiceM5665/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1180506,75615,54471,913, $ua, '23022-22835-17470-18092');
  }
  $ua = 'Spice M5700';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(243930,75615,54471,913, $ua, '15621-22835-17470-18092');
  }
  $ua = 'SpiceM5395/MTK Release/01.01.2012 Browser/wap2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1273545,75615,54471,913, $ua, '23050-22835-17470-18092');
  }
  $ua = 'Spice M5252';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(440584,75615,54471,913, $ua, '16933-22835-17470-18092');
  }
  $ua = 'Spice M5170';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(240569,75615,54471,913, $ua, '15591-22835-17470-18092');
  }
  $ua = 'Spice M6100';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1431752,75615,54471,913, $ua, '23277-22835-17470-18092');
  }
  $ua = 'Spice M5570';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(254197,75615,54471,913, $ua, '15581-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.5; en-US; Spice_MI-352) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1294393,90522,645789,913, $ua, '21851-5629-18326-18092');
  }
  $ua = 'Spice M9000';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(702989,75615,54471,913, $ua, '23376-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.5; en-US; Spice_Mi-351) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1331990,90522,645789,913, $ua, '23016-5629-18326-18092');
  }
  $ua = 'Spice QT68';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(240425,75615,54471,913, $ua, '15589-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; Spice_Mi-502) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1436142,576960,645789,913, $ua, '23017-18066-18326-18092');
  }
  $ua = 'Spice M-940 Gold/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1, Spice M-940 Gold/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(182645,75615,54471,913, $ua, '16905-22835-17470-18092');
  }
  $ua = 'Spice M-940 Gold/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(182645,75615,54471,913, $ua, '16905-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.4; en-US; Spice_Mi-320) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1192185,90522,645789,913, $ua, '23463-5629-18326-18092');
  }
  $ua = 'Spice M5750';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(251877,75615,54471,913, $ua, '15711-22835-17470-18092');
  }
  $ua = 'UP.Browser/5.0/Spice G6550';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(44218,27598,52405,913, $ua, '15364-17017-4948-18092');
  }
  $ua = 'Spice QT-57/(2010.06.22) S005/WAP2.0 Profile/MIDP2.0 Configuration/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(379949,75615,54471,913, $ua, '16856-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; Spice_Mi-355) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1041529,90522,645789,913, $ua, '21039-5629-18326-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 4.0.4; en-US; Spice_Mi-435) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1295671,576960,645789,913, $ua, '21850-18066-18326-18092');
  }
  $ua = 'Spice M5454';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1472977,75615,54471,913, $ua, '16800-22835-17470-18092');
  }
  $ua = 'Spice S7000/(X)S006/WAP2.0 Profile/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(751006,75615,54471,913, $ua, '16885-22835-17470-18092');
  }
  $ua = 'Spice D88';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(428220,75615,54471,913, $ua, '17118-22835-17470-18092');
  }
  $ua = 'Spice D88/WAP2.0';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(428220,75615,54471,913, $ua, '17118-22835-17470-18092');
  }
  $ua = 'UCWEB/2.0 (Linux; U; Adr 2.3.6; en-US; Spice_Mi-425) U2/1.0.0 UCBrowser/8.2.0.242 U2/1.0.0 Mobile';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(950160,90522,645789,913, $ua, '21036-5629-18326-18092');
  }
  $ua = 'Spice M5262';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(1232870,75615,54471,913, $ua, '16778-22835-17470-18092');
  }
  $ua = 'Spice S580';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(432770,75615,54471,913, $ua, '16995-22835-17470-18092');
  }
  $ua = 'Spice_M6400/WapBrowserConfiguration2.0/MIDP2.0/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(287076,75615,54471,913, $ua, '12791-22835-17470-18092');
  }
  $ua = 'Spice/1.0/QT-68/Obigo Browser/Q03C Browser/Q03C MMS/1.0/MIDP-2.0 Configuration/CLDC-1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(240425,75615,98811,913, $ua, '15589-22835-3807-18092');
  }
  $ua = 'Spice S950 NF-Browser/3.3 Openwave-MMS/4.5 IA-Java/1.0 Profile/MIDP2.0/CLDC1.1';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(355045,75615,37321,913, $ua, '14298-22835-3601-18092');
  }
  $ua = 'Spice S5330';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(440944,75615,54471,913, $ua, '16986-22835-17470-18092');
  }
  $ua = 'Spice S650/KAA736_0.90.626 Nucleus/1.0 MTK/6223 Release/06.26.2007 Browser/Teleca_obigo Profile/MIDP-1.0 Configuration/CLDC-1.0';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(432267,321377,54471,913, $ua, '17061-22857-17470-18092');
  }
  $ua = 'Spice S710';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(433274,75615,54471,913, $ua, '16989-22835-17470-18092');
  }
  $ua = 'Spice S5420';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(441449,75615,54471,913, $ua, '16924-22835-17470-18092');
  }
  $ua = 'Spice S820';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(440512,75615,54471,913, $ua, '17068-22835-17470-18092');
  }
  $ua = 'Spice S705';
  $ns = E90($useragent, $ua, $ls);
  if ($ns <= $ls) {
    if ($ns < $ls) {
      unset($dl);
      $ls = $ns;
    }
    $dl[] = array(442701,75615,54471,913, $ua, '16912-22835-17470-18092');
  }
  return $dl;
}
